"""Exact scalar PRESENT-80 reference with explicit big-endian conventions."""

from __future__ import annotations

from collections.abc import Sequence

BLOCK_BYTES = 8
KEY_BYTES = 10
ROUNDS = 31
MASK64 = (1 << 64) - 1
MASK80 = (1 << 80) - 1

SBOX = (0xC, 0x5, 0x6, 0xB, 0x9, 0x0, 0xA, 0xD, 0x3, 0xE, 0xF, 0x8, 0x4, 0x7, 0x1, 0x2)
INV_SBOX = tuple(SBOX.index(value) for value in range(16))
PBOX = tuple((16 * index) % 63 if index != 63 else 63 for index in range(64))
INV_PBOX = tuple(PBOX.index(value) for value in range(64))

# Appendix I of Bogdanov et al., PRESENT: An Ultra-Lightweight Block Cipher,
# CHES 2007, DOI 10.1007/978-3-540-74735-2_31.
PRESENT80_CHES2007_KATS = (
    {
        "key_hex": "00000000000000000000",
        "plaintext_hex": "0000000000000000",
        "ciphertext_hex": "5579c1387b228445",
    },
    {
        "key_hex": "ffffffffffffffffffff",
        "plaintext_hex": "0000000000000000",
        "ciphertext_hex": "e72c46c0f5945049",
    },
    {
        "key_hex": "00000000000000000000",
        "plaintext_hex": "ffffffffffffffff",
        "ciphertext_hex": "a112ffc72f68417b",
    },
    {
        "key_hex": "ffffffffffffffffffff",
        "plaintext_hex": "ffffffffffffffff",
        "ciphertext_hex": "3333dcd3213210d2",
    },
)

# ISO/IEC 29192-2:2012 Annex B.1.1.  This non-palindromic vector and its
# round-key checkpoints bind the external byte
# order, S-box nibble order, P-layer bit numbering, key rotation, counter bits,
# and final K32 whitening convention.
PRESENT80_ISO29192_B_1_1_KAT = {
    "key_hex": "0123456789abcdef0123",
    "plaintext_hex": "0123456789abcdef",
    "ciphertext_hex": "f8dd50531d973bde",
    "round_key_hex": {
        "1": "0123456789abcdef",
        "2": "1024602468acf135",
        "31": "b57108e6e7d71e08",
        "32": "5d37d6ae211cdcf5",
    },
}

# Non-palindromic orientation sentinels generated by a direct transcription of
# the archived lightweightcrypto.org pypresent v1.0 implementation.  They are
# separate from the four published CHES KATs and specifically exercise byte,
# nibble, P-layer-bit, and 80-bit key-register orientation.
PRESENT80_ORIENTATION_SENTINELS = (
    {
        "key_hex": "00010203040506070809",
        "plaintext_hex": "0123456789abcdef",
        "ciphertext_hex": "f7f0bfafd3ceb06c",
    },
    {
        "key_hex": "0123456789abcdef0123",
        "plaintext_hex": "fedcba9876543210",
        "ciphertext_hex": "cb7d344f360de3b1",
    },
)


def key_bytes_to_parts(key: bytes) -> tuple[int, int, int]:
    """Return `(high16, middle32, low32)` from the 10 big-endian key bytes."""

    if len(key) != KEY_BYTES:
        raise ValueError("PRESENT-80 requires exactly 10 key bytes")
    value = int.from_bytes(key, "big")
    return (value >> 64) & 0xFFFF, (value >> 32) & 0xFFFFFFFF, value & 0xFFFFFFFF


def key_parts_to_int(high16: int, middle32: int, low32: int) -> int:
    if high16 < 0 or high16 > 0xFFFF:
        raise ValueError("PRESENT-80 high key part must fit in uint16")
    if middle32 < 0 or middle32 > 0xFFFFFFFF:
        raise ValueError("PRESENT-80 middle key part must fit in uint32")
    if low32 < 0 or low32 > 0xFFFFFFFF:
        raise ValueError("PRESENT-80 low key part must fit in uint32")
    return (high16 << 64) | (middle32 << 32) | low32


def key_schedule(key_80: int) -> list[int]:
    if key_80 < 0 or key_80 > MASK80:
        raise ValueError("PRESENT-80 key must fit in 80 bits")
    register = key_80
    round_keys: list[int] = []
    for round_index in range(1, ROUNDS + 2):
        round_keys.append(register >> 16)
        if round_index > ROUNDS:
            break
        register = ((register << 61) | (register >> 19)) & MASK80
        register = (register & ((1 << 76) - 1)) | (SBOX[register >> 76] << 76)
        register ^= round_index << 15
    return round_keys


def sbox_layer(state: int) -> int:
    output = 0
    for index in range(16):
        output |= SBOX[(state >> (4 * index)) & 0xF] << (4 * index)
    return output


def inverse_sbox_layer(state: int) -> int:
    output = 0
    for index in range(16):
        output |= INV_SBOX[(state >> (4 * index)) & 0xF] << (4 * index)
    return output


def permutation_layer(state: int) -> int:
    output = 0
    for source, destination in enumerate(PBOX):
        output |= ((state >> source) & 1) << destination
    return output


def inverse_permutation_layer(state: int) -> int:
    output = 0
    for source, destination in enumerate(INV_PBOX):
        output |= ((state >> source) & 1) << destination
    return output


def encrypt_int(plaintext: int, round_keys: Sequence[int]) -> int:
    if plaintext < 0 or plaintext > MASK64:
        raise ValueError("PRESENT plaintext must fit in 64 bits")
    if len(round_keys) != ROUNDS + 1:
        raise ValueError("PRESENT-80 requires exactly 32 round keys")
    state = plaintext
    for round_index in range(ROUNDS):
        state = permutation_layer(sbox_layer(state ^ int(round_keys[round_index])))
    return (state ^ int(round_keys[ROUNDS])) & MASK64


def decrypt_int(ciphertext: int, round_keys: Sequence[int]) -> int:
    if ciphertext < 0 or ciphertext > MASK64:
        raise ValueError("PRESENT ciphertext must fit in 64 bits")
    if len(round_keys) != ROUNDS + 1:
        raise ValueError("PRESENT-80 requires exactly 32 round keys")
    state = ciphertext ^ int(round_keys[ROUNDS])
    for round_index in range(ROUNDS - 1, -1, -1):
        state = inverse_sbox_layer(inverse_permutation_layer(state))
        state ^= int(round_keys[round_index])
    return state & MASK64


def encrypt_block(plaintext: bytes, key: bytes) -> bytes:
    if len(plaintext) != BLOCK_BYTES:
        raise ValueError("PRESENT plaintext blocks contain exactly 8 bytes")
    if len(key) != KEY_BYTES:
        raise ValueError("PRESENT-80 requires exactly 10 key bytes")
    ciphertext = encrypt_int(
        int.from_bytes(plaintext, "big"), key_schedule(int.from_bytes(key, "big"))
    )
    return ciphertext.to_bytes(BLOCK_BYTES, "big")


def decrypt_block(ciphertext: bytes, key: bytes) -> bytes:
    if len(ciphertext) != BLOCK_BYTES:
        raise ValueError("PRESENT ciphertext blocks contain exactly 8 bytes")
    if len(key) != KEY_BYTES:
        raise ValueError("PRESENT-80 requires exactly 10 key bytes")
    plaintext = decrypt_int(
        int.from_bytes(ciphertext, "big"), key_schedule(int.from_bytes(key, "big"))
    )
    return plaintext.to_bytes(BLOCK_BYTES, "big")


def _verify(vectors: Sequence[dict[str, str]]) -> list[dict[str, object]]:
    rows = []
    for vector in vectors:
        actual = encrypt_block(
            bytes.fromhex(vector["plaintext_hex"]), bytes.fromhex(vector["key_hex"])
        ).hex()
        rows.append(
            {
                **vector,
                "actual_ciphertext_hex": actual,
                "pass": actual == vector["ciphertext_hex"],
            }
        )
    return rows


def verify_ches2007_kats() -> list[dict[str, object]]:
    return _verify(PRESENT80_CHES2007_KATS)


def verify_iso29192_b_1_1() -> dict[str, object]:
    vector = PRESENT80_ISO29192_B_1_1_KAT
    key = int(vector["key_hex"], 16)
    round_keys = key_schedule(key)
    actual = encrypt_int(int(vector["plaintext_hex"], 16), round_keys)
    actual_round_keys = {
        label: f"{round_keys[int(label) - 1]:016x}"
        for label in vector["round_key_hex"]
    }
    return {
        **vector,
        "actual_ciphertext_hex": f"{actual:016x}",
        "actual_round_key_hex": actual_round_keys,
        "ciphertext_pass": f"{actual:016x}" == vector["ciphertext_hex"],
        "round_keys_pass": actual_round_keys == vector["round_key_hex"],
        "pass": (
            f"{actual:016x}" == vector["ciphertext_hex"]
            and actual_round_keys == vector["round_key_hex"]
        ),
    }


def verify_orientation_sentinels() -> list[dict[str, object]]:
    return _verify(PRESENT80_ORIENTATION_SENTINELS)
