"""Exact scalar PRESENT-128 reference with explicit big-endian conventions."""

from __future__ import annotations

from collections.abc import Sequence

BLOCK_BYTES = 8
KEY_BYTES = 16
ROUNDS = 31
MASK64 = (1 << 64) - 1
MASK128 = (1 << 128) - 1

SBOX = (0xC, 0x5, 0x6, 0xB, 0x9, 0x0, 0xA, 0xD, 0x3, 0xE, 0xF, 0x8, 0x4, 0x7, 0x1, 0x2)
INV_SBOX = tuple(SBOX.index(value) for value in range(16))
PBOX = tuple((16 * index) % 63 if index != 63 else 63 for index in range(64))
INV_PBOX = tuple(PBOX.index(value) for value in range(64))

# The all-zero row is the official PRESENT-128 primitive gate already used by
# the repository.  The remaining boundary rows are local regression KATs,
# cross-checked against the independent legacy implementation in nano_ciphers.
PRESENT128_REFERENCE_KATS = (
    {
        "key_hex": "00000000000000000000000000000000",
        "plaintext_hex": "0000000000000000",
        "ciphertext_hex": "96db702a2e6900af",
    },
    {
        "key_hex": "ffffffffffffffffffffffffffffffff",
        "plaintext_hex": "0000000000000000",
        "ciphertext_hex": "13238c710272a5d8",
    },
    {
        "key_hex": "00000000000000000000000000000000",
        "plaintext_hex": "ffffffffffffffff",
        "ciphertext_hex": "3c6019e5e5edd563",
    },
    {
        "key_hex": "ffffffffffffffffffffffffffffffff",
        "plaintext_hex": "ffffffffffffffff",
        "ciphertext_hex": "628d9fbd4218e5b4",
    },
)
PRESENT128_OFFICIAL_ZERO_KAT = PRESENT128_REFERENCE_KATS[0]

# Local non-palindromic schedule trace.  It is deliberately separate from the
# published vectors and binds byte order, both top-nibble substitutions, the
# 128-bit rotate-left-61 operation, counter bits 66..62, and K32 whitening.
PRESENT128_ROUND_KEY_SENTINEL = {
    "key_hex": "000102030405060708090a0b0c0d0e0f",
    "plaintext_hex": "0123456789abcdef",
    "ciphertext_hex": "0e3dcaff311f1809",
    "round_key_hex": {
        "1": "0001020304050607",
        "2": "150121416181a1c1",
        "3": "b90004080c101418",
        "31": "a6a7d33563271366",
        "32": "47760455aebda684",
    },
}

# Non-palindromic local orientation sentinels generated by an independent
# direct transcription of the PRESENT-128 specification.  They exercise byte,
# nibble, P-layer-bit, and 128-bit key-register orientation.
PRESENT128_ORIENTATION_SENTINELS = (
    {
        "key_hex": "000102030405060708090a0b0c0d0e0f",
        "plaintext_hex": "0123456789abcdef",
        "ciphertext_hex": "0e3dcaff311f1809",
    },
    {
        "key_hex": "0123456789abcdeffedcba9876543210",
        "plaintext_hex": "fedcba9876543210",
        "ciphertext_hex": "f34a1e62e4b5b4d4",
    },
)


def key_bytes_to_parts(key: bytes) -> tuple[int, int, int]:
    """Return `(high64, middle32, low32)` from 16 big-endian key bytes."""

    if len(key) != KEY_BYTES:
        raise ValueError("PRESENT-128 requires exactly 16 key bytes")
    value = int.from_bytes(key, "big")
    return value >> 64, (value >> 32) & 0xFFFFFFFF, value & 0xFFFFFFFF


def key_parts_to_int(high64: int, middle32: int, low32: int) -> int:
    if high64 < 0 or high64 > MASK64:
        raise ValueError("PRESENT-128 high key part must fit in uint64")
    if middle32 < 0 or middle32 > 0xFFFFFFFF:
        raise ValueError("PRESENT-128 middle key part must fit in uint32")
    if low32 < 0 or low32 > 0xFFFFFFFF:
        raise ValueError("PRESENT-128 low key part must fit in uint32")
    return (high64 << 64) | (middle32 << 32) | low32


def key_schedule(key_128: int) -> list[int]:
    if key_128 < 0 or key_128 > MASK128:
        raise ValueError("PRESENT-128 key must fit in 128 bits")
    register = key_128
    round_keys: list[int] = []
    for round_index in range(1, ROUNDS + 2):
        round_keys.append(register >> 64)
        if round_index > ROUNDS:
            break
        register = ((register << 61) | (register >> 67)) & MASK128
        top = SBOX[(register >> 124) & 0xF]
        second = SBOX[(register >> 120) & 0xF]
        register = (register & ((1 << 120) - 1)) | (top << 124) | (second << 120)
        register ^= round_index << 62
    return round_keys


def sbox_layer(state: int) -> int:
    output = 0
    for index in range(16):
        output |= SBOX[(state >> (4 * index)) & 0xF] << (4 * index)
    return output


def inverse_sbox_layer(state: int) -> int:
    output = 0
    for index in range(16):
        output |= INV_SBOX[(state >> (4 * index)) & 0xF] << (4 * index)
    return output


def permutation_layer(state: int) -> int:
    output = 0
    for source, destination in enumerate(PBOX):
        output |= ((state >> source) & 1) << destination
    return output


def inverse_permutation_layer(state: int) -> int:
    output = 0
    for source, destination in enumerate(INV_PBOX):
        output |= ((state >> source) & 1) << destination
    return output


def encrypt_int(plaintext: int, round_keys: Sequence[int]) -> int:
    if plaintext < 0 or plaintext > MASK64:
        raise ValueError("PRESENT plaintext must fit in 64 bits")
    if len(round_keys) != ROUNDS + 1:
        raise ValueError("PRESENT-128 requires exactly 32 round keys")
    state = plaintext
    for round_index in range(ROUNDS):
        state = permutation_layer(sbox_layer(state ^ int(round_keys[round_index])))
    return (state ^ int(round_keys[ROUNDS])) & MASK64


def decrypt_int(ciphertext: int, round_keys: Sequence[int]) -> int:
    if ciphertext < 0 or ciphertext > MASK64:
        raise ValueError("PRESENT ciphertext must fit in 64 bits")
    if len(round_keys) != ROUNDS + 1:
        raise ValueError("PRESENT-128 requires exactly 32 round keys")
    state = ciphertext ^ int(round_keys[ROUNDS])
    for round_index in range(ROUNDS - 1, -1, -1):
        state = inverse_sbox_layer(inverse_permutation_layer(state))
        state ^= int(round_keys[round_index])
    return state & MASK64


def encrypt_block(plaintext: bytes, key: bytes) -> bytes:
    if len(plaintext) != BLOCK_BYTES:
        raise ValueError("PRESENT plaintext blocks contain exactly 8 bytes")
    if len(key) != KEY_BYTES:
        raise ValueError("PRESENT-128 requires exactly 16 key bytes")
    ciphertext = encrypt_int(
        int.from_bytes(plaintext, "big"), key_schedule(int.from_bytes(key, "big"))
    )
    return ciphertext.to_bytes(BLOCK_BYTES, "big")


def decrypt_block(ciphertext: bytes, key: bytes) -> bytes:
    if len(ciphertext) != BLOCK_BYTES:
        raise ValueError("PRESENT ciphertext blocks contain exactly 8 bytes")
    if len(key) != KEY_BYTES:
        raise ValueError("PRESENT-128 requires exactly 16 key bytes")
    plaintext = decrypt_int(
        int.from_bytes(ciphertext, "big"), key_schedule(int.from_bytes(key, "big"))
    )
    return plaintext.to_bytes(BLOCK_BYTES, "big")


def _verify(vectors: Sequence[dict[str, str]]) -> list[dict[str, object]]:
    rows = []
    for vector in vectors:
        actual = encrypt_block(
            bytes.fromhex(vector["plaintext_hex"]), bytes.fromhex(vector["key_hex"])
        ).hex()
        rows.append(
            {
                **vector,
                "actual_ciphertext_hex": actual,
                "pass": actual == vector["ciphertext_hex"],
            }
        )
    return rows


def verify_reference_kats() -> list[dict[str, object]]:
    return _verify(PRESENT128_REFERENCE_KATS)


def verify_official_zero_kat() -> dict[str, object]:
    return _verify((PRESENT128_OFFICIAL_ZERO_KAT,))[0]


def verify_round_key_sentinel() -> dict[str, object]:
    vector = PRESENT128_ROUND_KEY_SENTINEL
    key = int(vector["key_hex"], 16)
    round_keys = key_schedule(key)
    actual = encrypt_int(int(vector["plaintext_hex"], 16), round_keys)
    actual_round_keys = {
        label: f"{round_keys[int(label) - 1]:016x}"
        for label in vector["round_key_hex"]
    }
    return {
        **vector,
        "actual_ciphertext_hex": f"{actual:016x}",
        "actual_round_key_hex": actual_round_keys,
        "ciphertext_pass": f"{actual:016x}" == vector["ciphertext_hex"],
        "round_keys_pass": actual_round_keys == vector["round_key_hex"],
        "pass": (
            f"{actual:016x}" == vector["ciphertext_hex"]
            and actual_round_keys == vector["round_key_hex"]
        ),
    }


def verify_orientation_sentinels() -> list[dict[str, object]]:
    return _verify(PRESENT128_ORIENTATION_SENTINELS)
